[package]
name = "passgen-desktop"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A simple password generator."
authors = ["Mamontov Konstantin <k@mamont.xyz>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
eframe = { version = "*", default-features = false, features = ["default_fonts", "wgpu", "persistence"] }

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
tracing-wasm = "0.2"
wasm-bindgen-futures = "0.4"


# Reduce the size of the executable  file:
[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
panic = 'abort'
strip = true

[build-dependencies]
windows_exe_info = "*"

[dependencies.winit]
# version = "*"
version = "*"
features = ["default"]
